"""init3

Revision ID: 2e1ce866b9eb
Revises: 5b22481e2bc2
Create Date: 2023-11-22 14:33:17.591236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1ce866b9eb'
down_revision = '5b22481e2bc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DailyStockReports', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('DailyStockReports', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_DailyStockReports_date'), 'DailyStockReports', ['date'], unique=False)
    op.create_index(op.f('ix_DailyStockReports_product_id'), 'DailyStockReports', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DailyStockReports_product_id'), table_name='DailyStockReports')
    op.drop_index(op.f('ix_DailyStockReports_date'), table_name='DailyStockReports')
    op.alter_column('DailyStockReports', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('DailyStockReports', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
