"""add exchrates

Revision ID: 534a0f468b10
Revises: 74c038405575
Create Date: 2023-12-03 18:50:54.444429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534a0f468b10'
down_revision = '74c038405575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('usd_tl_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('eur_usd_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('DailyStockReports_product_id_fkey', 'DailyStockReports', type_='foreignkey')
    op.create_foreign_key(None, 'DailyStockReports', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('companies_user_id_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('contacts_user_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('purchases_user_id_fkey', 'purchases', type_='foreignkey')
    op.drop_constraint('purchases_company_id_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'purchases', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_company_id_fkey', 'purchases', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('purchases_user_id_fkey', 'purchases', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_user_id_fkey', 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key('companies_user_id_fkey', 'companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'DailyStockReports', type_='foreignkey')
    op.create_foreign_key('DailyStockReports_product_id_fkey', 'DailyStockReports', 'products', ['product_id'], ['id'])
    op.drop_table('exchrate')
    # ### end Alembic commands ###
