"""purchse fix

Revision ID: 8f77add7eb3e
Revises: b5eac1d7c951
Create Date: 2023-11-24 07:59:46.156920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f77add7eb3e'
down_revision = 'b5eac1d7c951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ukrainian_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'russian_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'turkish_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('purchases', sa.Column('notes', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'notes')
    op.alter_column('products', 'turkish_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'russian_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'ukrainian_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
