"""add exchrates2

Revision ID: a31007742ccb
Revises: 534a0f468b10
Create Date: 2023-12-03 19:49:23.755417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a31007742ccb'
down_revision = '534a0f468b10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('usd_tl_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('eur_usd_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exchrate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchrate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usd_tl_rate', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('eur_usd_rate', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='exchrate_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='exchrate_pkey')
    )
    op.drop_table('exchrates')
    # ### end Alembic commands ###
