"""drop purchase

Revision ID: b4f74da1f8d1
Revises: 81ff08147ca0
Create Date: 2023-11-24 12:59:47.660075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f74da1f8d1'
down_revision = '81ff08147ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('operation_type', sa.Enum('income', 'outcome', name='operation_types'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_tl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transfer_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_duties', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sum_total_tl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('appr_ex_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sum_total_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('cost_per_mt_tl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_per_mt_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    # ### end Alembic commands ###
